### ISSUE TITLE
dynamic subject-specific predictions

### ISSUE THREAD

**Issue by Mathematinho** [jknowles/merTools#117]
i have a merMod object (random intercept random slope) fitted from the current data. if i have new data from a new subject not seen in the fitted data, and i want to do longitudinal predictions on this subject. what would be the best approach with predictInterval? Do I have to refit the merMod object with new subject data appended? or there is an easier approach. Thanks in advance.

**Comment by Mathematinho** [comment]
a follow up question is that when i predict and extrapolate a subject in my dataset. i was expecting that the prediction where i have data would have much narrower confidence interval than there were the extrapolation was estimated.

**Comment by jknowles** [comment]
Without knowing the data or the structure it is hard to say why this is happening (that's a better question for StackOverflow than for here). In many cases though you will want to turn off the residual variance component of the prediction because if the model does not fit the data really well than  most of the uncertainty in predictors will apply to all subjects, observed and unobserved alike, because the model is uncertain about everything. 

The prediction question for a new subject is covered in the vignette. You have a number of options to simulate unobserved subject data and apply `predictInterval` to that new data.
