### ISSUE TITLE
Incompatibily of the merTools package with the select function from dplyr

### ISSUE THREAD

**Issue by armandfavrot** [jknowles/merTools#129]
Hi, I have noticed that the select function from dplyr is not compatible with the merTools package : when the merTools package is loaded, the select function won't work anymore.

Here is a reproducible example : 

```
library(dplyr)

df = data.frame(x = rnorm(5), y = rnorm(5), z = rnorm(5))

df %>% select(x, y)

library(merTools)

df %>% select(x, y)
```

**Comment by TylerSagendorf** [comment]
@armandfavrot This is just a namespace conflict. Both packages have a `select` function. The one from `dplyr` is overwritten by the one from `merTools` because `merTools` was loaded last. This is not an uncommon occurrence, especially when functions are given simple verbs as names. Use `dplyr::select` to specify that you want the function from `dplyr`.

**Comment by jknowles** [comment]
Yes, it isn't the `select` function from `merTools` this is a longstanding issue with the `MASS` package which `merTools` depends on indirectly unfortunately.
