### ISSUE TITLE
Import foreach?

### ISSUE THREAD

**Issue by elinw** [jknowles/merTools#71]
I was getting all kinds of errors when trying the shiny app (really cool). Eventually I realized that I had to install the foreach package to get it to work.  I think you might want to move foreach out of suggested into Imports in DESCRIPTION.

**Comment by elinw** [comment]
https://github.com/jknowles/merTools/pull/72

**Comment by jknowles** [comment]
Thanks @elinw for PR #72 . I haven't had a chance to test it on a "vanilla" R install -- I'm pretty sure we didn't catch this because by now all my test machines have foreach installed and we skip any unit tests for `shinyMer` on `CI` because I don't know how to make that work well. I'll look into this soon, but it seems like a good fix. Thanks.

**Comment by elinw** [comment]
Closing this since the PR was merged. :)
